# REQUIRED VARIABLES

variable "api_management_id" {
  description = "(REQUIRED) The ID of the API Management service for which to configure Custom Domains. Changing this forces a new API Management Custom Domain resource to be created."
  type        = string

}

# OPTIONAL VARIABLES

variable "developer_portal" {
  description = "One or more 'developer_portal' blocks."
  type        = map(map(any))
  default     = null
}
#
# developer_portal block structure        :
#   host_name (string)                      : (REQUIRED) The Hostname to use for the corresponding endpoint.
#   certificate (string)                    : The Base64 Encoded Certificate. (Mutually exclusive with 'key_vault_id'.)
#   certificate_password (string)           : The password associated with the certificate provided above.
#   key_vault_id (string)                   : The ID of the Key Vault Secret containing the SSL Certificate, which must be should be of the type application/x-pkcs12.
#   negotiate_client_certificate (bool)     : Should Client Certificate Negotiation be enabled for this Hostname? Defaults to 'false'.
#   ssl_keyvault_identity_client_id (string): System or User Assigned Managed identity clientId as generated by Azure AD, which has 'GET' access to the keyVault containing the SSL certificate.


variable "management" {
  description = "One or more 'management' blocks."
  type        = map(map(any))
  default     = null
}
#
# management block structure              :
#   host_name (string)                      : (REQUIRED) The Hostname to use for the corresponding endpoint.
#   certificate (string)                    : The Base64 Encoded Certificate. (Mutually exclusive with 'key_vault_id'.)
#   certificate_password (string)           : The password associated with the certificate provided above.
#   key_vault_id (string)                   : The ID of the Key Vault Secret containing the SSL Certificate, which must be should be of the type application/x-pkcs12.
#   negotiate_client_certificate (bool)     : Should Client Certificate Negotiation be enabled for this Hostname? Defaults to 'false'.
#   ssl_keyvault_identity_client_id (string): System or User Assigned Managed identity clientId as generated by Azure AD, which has 'GET' access to the keyVault containing the SSL certificate.


variable "portal" {
  description = "One or more 'portal' blocks."
  type        = map(map(any))
  default     = null
}
#
# portal block structure                  :
#   host_name (string)                      : (REQUIRED) The Hostname to use for the corresponding endpoint.
#   certificate (string)                    : The Base64 Encoded Certificate. (Mutually exclusive with 'key_vault_id'.)
#   certificate_password (string)           : The password associated with the certificate provided above.
#   key_vault_id (string)                   : The ID of the Key Vault Secret containing the SSL Certificate, which must be should be of the type application/x-pkcs12.
#   negotiate_client_certificate (bool)     : Should Client Certificate Negotiation be enabled for this Hostname? Defaults to 'false'.
#   ssl_keyvault_identity_client_id (string): System or User Assigned Managed identity clientId as generated by Azure AD, which has 'GET' access to the keyVault containing the SSL certificate.


variable "gateway" {
  description = "One or more 'gateway' blocks."
  type        = map(map(any))
  default     = null
}
#
# gateway block structure                 :
#   host_name (string)                      : (REQUIRED) The Hostname to use for the API Proxy Endpoint.
#   certificate (string)                    : The Base64 Encoded Certificate. (Mutually exclusive with 'key_vault_id'.)
#   certificate_password (string)           : The password associated with the certificate provided above.
#   default_ssl_binding (bool)              : Is the certificate associated with this Hostname the Default SSL Certificate? This is used when an SNI header isn't specified by a client. Defaults to 'false'.
#   key_vault_id (string)                   : The ID of the Key Vault Secret containing the SSL Certificate, which must be should be of the type application/x-pkcs12.
#   negotiate_client_certificate (bool)     : Should Client Certificate Negotiation be enabled for this Hostname? Defaults to 'false'.
#   ssl_keyvault_identity_client_id (string): System or User Assigned Managed identity clientId as generated by Azure AD, which has 'GET' access to the keyVault containing the SSL certificate.


variable "scm" {
  description = "One or more 'scm' blocks."
  type        = map(map(any))
  default     = null
}
#
# scm block structure                     :
#   host_name (string)                      : (REQUIRED) The Hostname to use for the corresponding endpoint.
#   certificate (string)                    : The Base64 Encoded Certificate. (Mutually exclusive with 'key_vault_id'.)
#   certificate_password (string)           : The password associated with the certificate provided above.
#   key_vault_id (string)                   : The ID of the Key Vault Secret containing the SSL Certificate, which must be should be of the type application/x-pkcs12.
#   negotiate_client_certificate (bool)     : Should Client Certificate Negotiation be enabled for this Hostname? Defaults to 'false'.
#   ssl_keyvault_identity_client_id (string): System or User Assigned Managed identity clientId as generated by Azure AD, which has 'GET' access to the keyVault containing the SSL certificate.


