output "expiration_date" {
  value = azurerm_virtual_desktop_host_pool_registration_info.this.expiration_date
}

output "hostpool_id" {
  value = azurerm_virtual_desktop_host_pool_registration_info.this.hostpool_id
}

output "id" {
  description = "The ID of the Virtual Desktop Host Pool Registration Info resource."
  value       = azurerm_virtual_desktop_host_pool_registration_info.this.id
}

output "token" {
  description = "The registration token generated by the Virtual Desktop Host Pool for registration of session hosts."
  value       = azurerm_virtual_desktop_host_pool_registration_info.this.token
}

